### ISSUE TITLE
AMP seems to allow @supports now

### ISSUE THREAD

**Issue by ashley-hebler** [tinovyatkin/postcss-amp#48]
From what I can tell AMP is cool with `@supports` in CSS now. I did a bit of digging on this and haven't quite figured out which commit they updated their validator to accept that, but based on the two references I'll add below, I'm thinking it might be okay to remove this line:

https://github.com/tinovyatkin/postcss-amp/blob/master/at-rules.js#L9

Their docs on https://amp.dev designate`@supports` as allowed.
![Screen Shot 2019-07-16 at 1 05 27 PM](https://user-images.githubusercontent.com/2974713/61318335-70403800-a7ca-11e9-9b88-d4e09b008761.png)
Link: https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/?format=websites#@-rules

I was trying find the point this became allowed and it seems like it happened around here:
https://github.com/ampproject/amphtml/issues/1315#issuecomment-176304867

**Comment by ashley-hebler** [comment]
Also this postcss plugin is a dream, thank you @tinovyatkin

**Comment by tinovyatkin** [comment]
Thank you! Will be released in 2.0 today
